# Generated by Django 5.2.8 on 2025-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Special Requirements'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('Takeaway', 'Takeaway')], default='Choose the table', max_length=10, verbose_name='Table Number'),
        ),
    ]
