# Generated by Django 5.2.8 on 2025-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_customer_name_order_notes_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='normal', max_length=100, verbose_name='Customer Name'),
        ),
    ]
