# Generated by Django 5.2.8 on 2025-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('Special Guests', 'Special Guests'), ('Normal Guests', 'Normal Guests')], default='Choose Customer Type', max_length=20, verbose_name='Customer Type'),
        ),
    ]
