# Generated by Django 5.2.8 on 2025-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_customer_name_order_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('Special Guests', 'Special Guests'), ('Normal Guests', 'Normal Guests')], max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('Takeaway', 'Takeaway')], max_length=10, verbose_name='Table Number'),
        ),
    ]
