# Generated by Django 5.2.8 on 2025-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_customer_type_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cooking', 'Cooking'), ('served', 'Served'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
